name: dbtc
description: Don't break the chain!

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  redux: ^3.0.0
  flutter_redux: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
